'use client';
import { useState } from 'react';
const banks = {"BAAC": ["BAAC", "ธ.ก.ส.", "ธนาคารเพื่อการเกษตรและสหกรณ์การเกษตร", "Bank for Agriculture and Agricultural Cooperatives"], "BAY": ["BAY", "กรุงศรีอยุธยา", "ธนาคารกรุงศรีอยุธยา", "Krungsri Bank", "KRUNGSRI"], "BBL": ["BBL", "กรุงเทพ", "ธนาคารกรุงเทพ", "Bangkok Bank"], "CIMB": ["CIMB", "ซีไอเอ็มบี", "ธนาคารซีไอเอ็มบี", "CIMB Thai Bank"], "CITI": ["CITI", "ซิตี้แบงก์", "ธนาคารซิตี้แบงก์", "citibank"], "GHB": ["GHB", "ธ.อ.ส.", "ธนาคารอาคารสงเคราะห์", "GH Bank"], "GSB": ["GSB", "ออมสิน", "ธนาคารออมสิน", "Government Savings Bank"], "HSBC": ["HSBC", "เอชเอสบีซี", "ธนาคารเอชเอสบีซี", "HSBC Bank"], "IBANK": ["IBANK", "อิสลามแห่งประเทศไทย", "ธนาคารอิสลามแห่งประเทศไทย", "Islamic Bank of Thailand"], "ICBC": ["ICBC", "ไอซีบีซี", "ธนาคารไอซีบีซี", "ICBC Thai Commercial Bank"], "KBANK": ["KBANK", "กสิกรไทย", "ธนาคารกสิกรไทย", "Kasikorn Bank", "K-BANK", "KASIKORN", "KASIKORNBANK", "LINE BK"], "KKP": ["KKP", "เกียรตินาคิน", "ธนาคารเกียรตินาคินภัทร", "Kiatnakin Phatra Bank"], "KTB": ["KTB", "กรุงไทย", "ธนาคารกรุงไทย", "Krungthai Bank", "KRUNGTHAI"], "LHB": ["LHB", "แลนด์ แอนด์ เฮ้าส์", "ธนาคารแลนด์ แอนด์ เฮ้าส์", "LH Bank", "LH BANK", "LHBANK"], "PromptPay": ["PromptPay", "พร้อมเพย์", "พร้อมเพย์", "PromptPay"], "SCB": ["SCB", "ไทยพาณิชย์", "ธนาคารไทยพาณิชย์", "The Siam Commercial Bank", "SIAM COMMERCIAL BANK"], "TCRB": ["TCRB", "ไทยเครดิต", "ธนาคารไทยเครดิต", "Thai Credit Bank"], "TISCO": ["TISCO", "ทิสโก้", "ธนาคารทิสโก้", "Tisco Bank"], "TrueMoney": ["TrueMoney", "ทรูมันนี่", "ทรูมันนี่", "True Money"], "TTB": ["TTB", "ทีเอ็มบีธนชาต", "ธนาคารทีเอ็มบีธนชาต", "TMBThanachart Bank", "TMB", "TBANK", "ธนชาต", "ทหารไทย"], "UOB": ["UOB", "ยูโอบี", "ธนาคารยูโอบี", "United Overseas Bank"]};
export function bankCode(value: string | null | undefined) { const n = String(value || "").trim().toLowerCase().replace(/[\s._-]/g, "").replace(/^ธนาคาร/, ""); if (!n) return null; for (const [code, names] of Object.entries(banks)) { if (names.some(name => name.toLowerCase().replace(/[\s._-]/g, "").replace(/^ธนาคาร/, "") === n)) return code; } return null; }
export default function BankLogo({ bank }: { bank?: string | null }) {
 const [failed, setFailed] = useState<string | null>(null);
 const code = bankCode(bank);
 if (!code || failed === code) return null;
 return <img src={`/banks/${code}.png`} alt="" aria-hidden="true" width={24} height={24} onError={() => setFailed(code)} style={{ display: 'inline-block', width: 24, height: 24, objectFit: 'contain', verticalAlign: 'middle', marginRight: 6 }} />;
}
